name: Hexo-make

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Use Python3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax

    - name: Clone Lib
      run: |
        git clone --depth 1 --branch master https://${GH_REF} my_build/
        cd my_build
        git clone --depth 1 --branch master "https://${MY_KEY}@${GH_THEME}" themes/next/
        git clone --depth 1 --branch master "https://${CO_TOKEN}@${GH_IMG}" source/photos/images/
      env:
        MY_KEY: ${{ secrets.MY_KEY }}
        CO_TOKEN: ${{ secrets.CO_TOKEN }}
        GH_THEME: github.com/liziwl/hexo-theme-next-mod.git
        GH_IMG: e.coding.net/liziwl/BlogPhotos.git
        GH_REF: github.com/liziwl/blog.git

    - name: npm install and setup env
      run: |
        cd my_build
        npm install hexo-cli -g # 安装hexo插件
        npm install
        pip install -r requirements.txt

    - name: Hexo build
      run: |
        cd my_build
        hexo clean
        hexo generate
        cp ./source/photos/photoslist.json ./public/photos/
      # fix JSON format
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.MY_KEY }}
        publish_dir: ./my_build/public
        publish_branch: gh-pages  # default: gh-pages
        force_orphan: true # only remain last commit
        # cname: blog.liziwl.cn

    # - name: setup aliyun oss
    #   uses: manyuanrong/setup-ossutil@master
    #   with:
    #     endpoint: oss-accelerate.aliyuncs.com
    #     access-key-id: ${{ secrets.OSS_KEY_ID }}
    #     access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

    # - name: cp files to aliyun
    #   run: ossutil cp -rf ./my_build/public oss://liziwl-blog/

    - name: Deploy to coding
      run: |
        cd my_build
        sha=$(git rev-parse --short HEAD)
        mkdir -p /tmp/liziwl_page_push
        cp -r ./public/* /tmp/liziwl_page_push
        cd /tmp/liziwl_page_push
        git init
        git config user.name "liziwl"
        git config user.email "leezisy@gmail.com"
        git remote add origin "https://${CODING_USER}:${CODING_PERSONAL_TOKEN}@${CODING_URL}"
        git add .
        git commit -m "Deploy ${sha}"
        git push -u -f origin master
      env:
        CODING_USER: ${{ secrets.CODING_USER }}
        CODING_PERSONAL_TOKEN: ${{ secrets.CODING_PERSONAL_TOKEN }}
        CODING_URL: "e.coding.net/liziwl/liziwl-page/blog-page.git"
