name: Hexo-make

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Clone Lib
      run: |
        git clone --depth 1 --branch master https://${GH_REF} my_build/
        cd my_build
        git clone --depth 1 --branch master "https://${MY_KEY}@${GH_THEME}" themes/next/
        git clone --depth 1 --branch master "https://${CO_TOKEN}@${GH_IMG}" source/photos/images/
      env:
        MY_KEY: ${{ secrets.MY_KEY }}
        CO_TOKEN: ${{ secrets.CO_TOKEN }}
        GH_THEME: github.com/liziwl/hexo-theme-next-mod.git
        GH_IMG: e.coding.net/liziwl/BlogPhotos.git
        GH_REF: github.com/liziwl/blog.git

    - name: npm install and setup env
      run: |
        cd my_build
        npm install hexo-cli -g # 安装hexo插件
        npm install

    - name: Hexo build
      run: |
        cd my_build
        hexo clean
        hexo generate
        cp ./source/photos/photoslist.json ./public/photos/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.MY_KEY }}
        publish_dir: ./my_build/public
        publish_branch: gh-pages  # default: gh-pages
        force_orphan: true # only remain last commit
        # cname: blog.liziwl.cn

    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-accelerate.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

    - name: cp files to aliyun
      run: ossutil cp -rf ./my_build/public oss://liziwl-blog/
